symptoms ="⚫ The most common symptoms of COVID-19 are fever, tiredness, and dry cough. \n⚫ Some patients may have aches and pains, nasal congestion, runny nose, sore throat or diarrhea. These symptoms are usually mild and begin gradually.\n⚫Some people become infected but don’t develop any symptoms and don't feel unwell. \n⚫ Most people (about 80%) recover from the disease without needing special treatment.\n⚫ Around 1 out of every 6 people who gets COVID-19 becomes seriously ill and develops difficulty breathing. \n⚫ Older people, and those with underlying medical problems like high blood pressure, heart problems or diabetes, are more likely to develop serious illness. \n⚫ People with fever, cough and difficulty breathing should seek medical attention."

prevention = "⚫ Regularly and thoroughly clean your hands with an alcohol-based hand rub or wash them with soap and water. \nMaintain at least 1 metre (3 feet) distance between yourself and anyone who is coughing or sneezing. Avoid touching eyes, nose and mouth. \n⚫ Make sure you, and the people around you, follow good respiratory hygiene. This means covering your mouth and nose with your bent elbow or tissue when you cough or sneeze. Then dispose of the used tissue immediately. \n⚫ Stay home if you feel unwell. If you have a fever, cough and difficulty breathing, seek medical attention and call in advance. \n⚫Follow the directions of your local health authority. If possible, avoid traveling to places  – especially if you are an older person or have diabetes, heart or lung disease. \n⚫ Keep up to date on the latest COVID-19 hotspots (cities or local areas where COVID-19 is spreading widely). \n⚫ Self-isolate by staying at home if you begin to feel unwell, even with mild symptoms such as headache, low grade fever (37.3 C or above) and slight runny nose, until you recover. \n⚫ If you develop fever, cough and difficulty breathing, seek medical advice promptly as this may be due to a respiratory infection or other serious condition. Call in advance and tell your provider of any recent travel or contact with travelers."

treatment = "If you feel sick you should rest, drink plenty of fluid, and eat nutritious food. \n⚫ Stay in a separate room from other family members, and use a dedicated bathroom if possible. \n⚫ Clean and disinfect frequently touched surfaces. \n⚫ Everyone should keep a healthy lifestyle at home. \n⚫ Maintain a healthy diet, sleep, stay active, and make social contact with loved ones through the phone or internet. Children need extra love and attention from adults during difficult times. \n⚫ Keep to regular routines and schedules as much as possible. \n⚫ It is normal to feel sad, stressed, or confused during a crisis. \n⚫ Talking to people you trust, such as friends and family, can help. If you feel overwhelmed, talk to a health worker or counsellor."






